### ISSUE TITLE
Admin - Add Term / Place type to Blacklist

### ISSUE THREAD

**Issue by erikschlegel** [CatalystCode/project-fortis-interfaces#84]
**Task Goal:** Currently the blacklist filter serves the purpose of a conjunctive filter, which excludes any event that happens to mention all the phrases within the blacklist. For example, if you have a tweet `donald trump won the election. Still coping`, and you're blacklist item is `['trump', 'election', 'coping']`, then that tweet would be ignored. If your blacklist was `['trump', 'donald', 'election', 'coping']` then that event would pass the blacklist check and processed in Fortis. 
![image](https://user-images.githubusercontent.com/7635865/30971155-c7ca766a-a42c-11e7-8be6-d4f4412c778f.png)

Based on user feedback from the Colombia office, users want take the same approach for mentioned places. So they want to blacklist specific places from Fortis. For example, if the tweet `a bombing occurred in colombia just a few minutes ago` and the blacklist record entry comprises of {terms: `['Columbia'], type: 'place'` then `Colombia` should be ignored as a recognized place'. Now, if the tweet is `a bombing occurred in colombia, 2 miles outside of Bogota just a few minutes ago`, then we should only detect `Bogota` as a mentioned place. 

*Newly Added Functionality*
- Enhance the graphql `Settings/termBlacklist` service within the services repo to add the `type` field to the service. This should only be one of two values, `place` or `term`. 
- Enhance the graphql `Settings/modifyBlacklist` and `Settings/removeBlacklist` mutation service within the services repo to support the new field. 
- Add the type field to the React Datagrid. The default value should be `term` for newly added blacklist rows in the grid. 
- Modify the spark pipeline Blacklist DTO `com.microsoft.partnercatalyst.fortis.spark.transforms.topic.Blacklist`
- Also modify `KeywordExtractor.scala` to only look for blacklist items of type `term`. 
- Integrate  the blacklist terms of type `place` into `LocationsExtractor.scala` to remove any detected places where the lowercased name of both the detected place and the blacklisted place name match. 
- Add unit tests for this under the `test` package.

**Comment by NathanielRose** [comment]
@erikschlegel 

1. Need some local setup assistance as I am only seeing "Loading Watcher" displayed on the node application. Will run on my linux box to see if that changes. Does the interfaces node app need to connect to a cassandra cluster with data already exiting?

2. Would the adjustment in the dashboard start with editing the heatmap tiles method in `index.js`? I see that `bbox` is linked to the blacklist term setting.

**Comment by c-w** [comment]
@NathanielRose To run the interfaces project, you need two environment variables (as per [docs](https://github.com/CatalystCode/project-fortis-interfaces#development-setup)):

```sh
# would recommend to run this locally since you may need to make changes
# the repository is https://github.com/CatalystCode/project-fortis-services
export REACT_APP_SERVICE_HOST="http://localhost:8000"

# can just use the shared instance for this
export REACT_APP_FEATURE_SERVICE_HOST="http://fortis-features.eastus.cloudapp.azure.com"
```

The interfaces project talks to Cassandra via the [project-fortis-services](https://github.com/CatalystCode/project-fortis-services) project. For running this locally, you need a few environment variables (as per the [docs](https://github.com/CatalystCode/project-fortis-services#environment-variables)):

```sh
export CASSANDRA_CONTACT_POINTS="localhost"
export CASSANDRA_PASSWORD="cassandra"
export CASSANDRA_USERNAME="cassandra"
export ENABLE_V2=1
```

You can refer to the [docs](https://github.com/CatalystCode/project-fortis-services#setting-up-cassandra-on-windows-linux-subsystem-ubuntu) on how to set up Cassandra. After that's set up, run the [initial migration](https://github.com/CatalystCode/project-fortis-pipeline/blob/2f5d4e87f8bfc350a9ffc786c8723aa551d3e121/ops/storage-ddls/cassandra-setup.cql) to set up the schema for the database:

```sh
cqlsh < $(curl 'https://raw.githubusercontent.com/CatalystCode/project-fortis-pipeline/2f5d4e87f8bfc350a9ffc786c8723aa551d3e121/ops/storage-ddls/cassandra-setup.cql')
``` 

You'll also want some sample data in your Cassandra database so that the dashboard can surface something. You can use the sample data dump that @jcjimenez provided for this:

```sh
for table_dump in /path/to/fortis_cassandra/*.csv; do
  echo "COPY $(basename ${table_dump} .csv) FROM '${table_dump}' WITH null='null';" | cqlsh
done
```

After that's done, you'll be able to see the dashboard at http://localhost:3000/#/site/YOUR_SITE_NAME where YOUR_SITE_NAME can be gotten via:

```sh
echo 'SELECT sitename FROM fortis.sitesettings;' | cqlsh
```

**Comment by c-w** [comment]
The Cassandra DB doesn't have a type column, instead if has a islocation column, so this feature is implemented in terms of that column.

There is now a new UI for editing the blacklist is-location column:

![image](https://user-images.githubusercontent.com/1086421/34881009-4ea3c53c-f780-11e7-8608-690eb3f99a37.png)

The filtering based on locations was already implemented in the past: https://github.com/CatalystCode/project-fortis/commit/64674b671703a14ee0f9696a7a54f8d6e6a409f4.
